---
# .env
# Variables for the server node playbook
application_source_dir: "../../../../" #need to modify path
application_dest_dir: "/home/transcendence"
sendgrid_api_key: 'sendgrid_api_key'
smtp_from_email: 'email@gmail.com'
alert_email_recipient: 'email@gmail.com'
